version: 2
 
sources:
  - name: qwt_raw
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS_DB')}}"
    schema: "{{env_var('DBT_SOURCESCHEMA', 'RAW_DEV')}}"
    tables:
    - name: raw_customers
    - name: raw_products
    - name: raw_orders
    - name: raw_order_details
    - name: raw_employees
    - name: raw_office
    - name: raw_shipments
    - name: raw_suppliers