version: 2
 
sources:
  - name: qwt_raw
    database: qwt_analytics_db
    schema: raw_dev
    tables:
    - name: raw_customers
    - name: raw_products
    - name: raw_orders
    - name: raw_order_details
    - name: raw_employees
    - name: raw_office
    - name: raw_shipments
    - name: raw_suppliers